// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopFlickerAPI.Data;

#nullable disable

namespace ShopFlickerAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230920173635_addUsersToDb")]
    partial class addUsersToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopFlickerAPI.Models.LocalUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShopFlickerAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1.99,
                            CreatedDate = new DateTime(2023, 7, 20, 22, 36, 35, 160, DateTimeKind.Local).AddTicks(8520),
                            Desc = "Fresh carrots from the local farm.",
                            Name = "Carrots"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 2.4900000000000002,
                            CreatedDate = new DateTime(2023, 8, 20, 22, 36, 35, 160, DateTimeKind.Local).AddTicks(8544),
                            Desc = "Organic broccoli for a healthy diet.",
                            Name = "Broccoli"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1.79,
                            CreatedDate = new DateTime(2023, 6, 20, 22, 36, 35, 160, DateTimeKind.Local).AddTicks(8547),
                            Desc = "Leafy green spinach, perfect for salads.",
                            Name = "Spinach"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 2.9900000000000002,
                            CreatedDate = new DateTime(2023, 7, 20, 22, 36, 35, 160, DateTimeKind.Local).AddTicks(8549),
                            Desc = "Vine-ripened tomatoes for your recipes.",
                            Name = "Tomatoes"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 1.49,
                            CreatedDate = new DateTime(2023, 7, 20, 22, 36, 35, 160, DateTimeKind.Local).AddTicks(8551),
                            Desc = "Crunchy cucumbers for snacking.",
                            Name = "Cucumbers"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
